# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urlLong',
            new_name='url_long',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='urlShort',
            new_name='url_short',
        ),
    ]
