# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrl', '0002_auto_20171214_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='redirectNumber',
            new_name='redirect_number',
        ),
    ]
