# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0003_auto_20171215_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_long',
            field=models.URLField(unique=True),
        ),
    ]
